### ISSUE TITLE
missing build:dev npm script for packages/react

### ISSUE THREAD

**Issue by pavanjadhaw** [magicbell-io/darkmagic#91]
I tried following the instructions in the readme and seems like we are missing the `build:dev` script
![CleanShot 2023-10-14 at 02 50 32@2x](https://github.com/magicbell-io/darkmagic/assets/26551780/f68b2dde-6a34-4c51-b7f4-7f46b1587f72)

**Comment by smeijer** [comment]
You're right. I've changed the build setup in #87, but didn't update the start scripts.

A PR would be welcome. Otherwise, I'll get to it as soon as I have a moment to spare.
